export const corRoxoClaroUm = "#9f79ec"
export const corRoxoEscuroUm = "#13062d"
export const corRoxoEscuroDois = "#391386"
export const corBranca = "#ebebfa"
export const corCinza = "#343333"
export const corPreta = "#000000"
export const font = "'Bitter', serif;"
